//Justification: Autogenerated code
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Data.Migrations.InitialDb.Up(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "<Pending>", Scope = "member", Target = "~M:SecretSanta.Data.Migrations.InitialDb.Down(Microsoft.EntityFrameworkCore.Migrations.MigrationBuilder)")]
